// src/client/components/Field.tsx
import type { ReactNode } from 'react'

/** Label + control + inline validation error. */
export default function Field({
  id,
  label,
  error,
  children,
}: {
  id: string
  label: string
  error?: unknown
  children: ReactNode
}) {
  return (
    <div className="field">
      <label htmlFor={id}>{label}</label>
      {children}
      {error ? (
        <p className="field-error" role="alert">
          {String(error)}
        </p>
      ) : null}
    </div>
  )
}

// src/client/components/Field.svelte
<script lang="ts">
  let {
    id,
    label,
    error,
    children,
  }: {
    id: string
    label: string
    error?: unknown
    children: import('svelte').Snippet
  } = $props()
</script>

<div class="field">
  <label for={id}>{label}</label>
  {@render children()}
  {#if error}
    <p class="field-error" role="alert">{String(error)}</p>
  {/if}
</div>
