// src/client/pages/ForgotPassword.tsx
import { Head, Link, useForm } from '@inertiajs/react'
import type { FormEvent } from 'react'
import AuthLayout from '../components/AuthLayout'
import Field from '../components/Field'

export default function ForgotPassword({ status }: { status?: string }) {
  const { data, setData, post, processing, errors, clearErrors } = useForm({ email: '' })

  const submit = (e: FormEvent) => {
    e.preventDefault()
    post('/forgot-password')
  }

  return (
    <AuthLayout>
      <Head title="Forgot password" />
      <h1>Reset your password</h1>
      <p className="auth-sub">Enter your email and we will send you a reset link.</p>

      {status === 'sent' ? (
        <div className="notice notice-success" role="status">
          If that email is registered, a reset link has been sent. Check your inbox.
        </div>
      ) : null}

      <form onSubmit={submit} noValidate>
        <Field id="email" label="Email" error={errors.email}>
          <input
            id="email"
            type="email"
            name="email"
            autoComplete="email"
            autoFocus
            value={data.email}
            onChange={(e) => {
              clearErrors('email')
              setData('email', e.target.value)
            }}
          />
        </Field>

        <button className="btn btn-primary btn-block" type="submit" disabled={processing}>
          {processing ? 'Sending…' : 'Send reset link'}
        </button>
      </form>

      <p className="auth-alt">
        Remembered it? <Link href="/login">Back to login</Link>
      </p>
    </AuthLayout>
  )
}

// src/client/pages/ForgotPassword.svelte
<script lang="ts">
  import { Link, useForm } from '@inertiajs/svelte'
  import AuthLayout from '../components/AuthLayout.svelte'
  import Field from '../components/Field.svelte'

  let { status = undefined }: { status?: string } = $props()

  const form = useForm({ email: '' })

  function submit(e: SubmitEvent) {
    e.preventDefault()
    form.post('/forgot-password')
  }
</script>

<svelte:head><title>Forgot password</title></svelte:head>

<AuthLayout>
  <h1>Reset your password</h1>
  <p class="auth-sub">Enter your email and we will send you a reset link.</p>

  {#if status === 'sent'}
    <div class="notice notice-success" role="status">
      If that email is registered, a reset link has been sent. Check your inbox.
    </div>
  {/if}

  <form onsubmit={submit} novalidate>
    <Field id="email" label="Email" error={form.errors.email}>
      <input
        id="email"
        type="email"
        name="email"
        autocomplete="email"
        autofocus
        bind:value={form.email}
        onchange={() => form.clearErrors('email')}
      />
    </Field>

    <button
      class="btn btn-primary btn-block"
      type="submit"
      disabled={form.processing}
    >
      {form.processing ? 'Sending…' : 'Send reset link'}
    </button>
  </form>

  <p class="auth-alt">
    Remembered it? <Link href="/login">Back to login</Link>
  </p>
</AuthLayout>
