// src/client/pages/NotFound.svelte
<script lang="ts">
  import { Link } from '@inertiajs/svelte'
  import Layout from '../components/Layout.svelte'
</script>

<svelte:head><title>Not found</title></svelte:head>

<Layout>
  <h1>404 — page not found</h1>
  <p class="page-sub">The page you are looking for does not exist.</p>
  <p>
    <Link href="/dashboard" class="btn btn-primary">Go to dashboard</Link>
  </p>
</Layout>

// src/client/pages/NotFound.tsx
import { Head, Link } from '@inertiajs/react'
import Layout from '../components/Layout'

export default function NotFound() {
  return (
    <Layout>
      <Head title="Not found" />
      <h1>404 — page not found</h1>
      <p className="page-sub">The page you are looking for does not exist.</p>
      <p>
        <Link href="/dashboard" className="btn btn-primary">
          Go to dashboard
        </Link>
      </p>
    </Layout>
  )
}
