// src/client/pages/Register.tsx
import { Head, Link, useForm } from '@inertiajs/react'
import type { FormEvent } from 'react'
import AuthLayout from '../components/AuthLayout'
import Field from '../components/Field'

export default function Register({ googleEnabled }: { googleEnabled: boolean }) {
  const { data, setData, post, processing, errors, clearErrors } = useForm({
    name: '',
    email: '',
    password: '',
  })

  const submit = (e: FormEvent) => {
    e.preventDefault()
    post('/register')
  }

  return (
    <AuthLayout>
      <Head title="Register" />
      <h1>Create your account</h1>
      <p className="auth-sub">Start building with the boilerplate in seconds.</p>

      {googleEnabled ? (
        <>
          <a className="btn btn-block btn-google" href="/auth/google">
            Register with Google
          </a>
          <div className="divider">or</div>
        </>
      ) : null}

      <form onSubmit={submit} noValidate>
        <Field id="name" label="Name" error={errors.name}>
          <input
            id="name"
            type="text"
            name="name"
            autoComplete="name"
            autoFocus
            value={data.name}
            onChange={(e) => {
              clearErrors('name')
              setData('name', e.target.value)
            }}
          />
        </Field>

        <Field id="email" label="Email" error={errors.email}>
          <input
            id="email"
            type="email"
            name="email"
            autoComplete="email"
            value={data.email}
            onChange={(e) => {
              clearErrors('email')
              setData('email', e.target.value)
            }}
          />
        </Field>

        <Field id="password" label="Password" error={errors.password}>
          <input
            id="password"
            type="password"
            name="password"
            autoComplete="new-password"
            value={data.password}
            onChange={(e) => {
              clearErrors('password')
              setData('password', e.target.value)
            }}
          />
          <p className="field-hint">At least 8 characters.</p>
        </Field>

        <button className="btn btn-primary btn-block" type="submit" disabled={processing}>
          {processing ? 'Creating account…' : 'Create account'}
        </button>
      </form>

      <p className="auth-alt">
        Already have an account? <Link href="/login">Log in</Link>
      </p>
    </AuthLayout>
  )
}

// src/client/pages/Register.svelte
<script lang="ts">
  import { Link, useForm } from '@inertiajs/svelte'
  import AuthLayout from '../components/AuthLayout.svelte'
  import Field from '../components/Field.svelte'

  let { googleEnabled = false }: { googleEnabled?: boolean } = $props()

  const form = useForm({ name: '', email: '', password: '' })

  function submit(e: SubmitEvent) {
    e.preventDefault()
    form.post('/register')
  }
</script>

<svelte:head><title>Register</title></svelte:head>

<AuthLayout>
  <h1>Create your account</h1>
  <p class="auth-sub">Start building with the boilerplate in seconds.</p>

  {#if googleEnabled}
    <a class="btn btn-block btn-google" href="/auth/google">
      Register with Google
    </a>
    <div class="divider">or</div>
  {/if}

  <form onsubmit={submit} novalidate>
    <Field id="name" label="Name" error={form.errors.name}>
      <input
        id="name"
        type="text"
        name="name"
        autocomplete="name"
        autofocus
        bind:value={form.name}
        onchange={() => form.clearErrors('name')}
      />
    </Field>

    <Field id="email" label="Email" error={form.errors.email}>
      <input
        id="email"
        type="email"
        name="email"
        autocomplete="email"
        bind:value={form.email}
        onchange={() => form.clearErrors('email')}
      />
    </Field>

    <Field id="password" label="Password" error={form.errors.password}>
      <input
        id="password"
        type="password"
        name="password"
        autocomplete="new-password"
        bind:value={form.password}
        onchange={() => form.clearErrors('password')}
      />
      <p class="field-hint">At least 8 characters.</p>
    </Field>

    <button class="btn btn-primary btn-block" type="submit" disabled={form.processing}>
      {form.processing ? 'Creating account…' : 'Create account'}
    </button>
  </form>

  <p class="auth-alt">
    Already have an account? <Link href="/login">Log in</Link>
  </p>
</AuthLayout>
